const CartActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  ADD_ITEM_WITH_QUANTITY: 'ADD_ITEM_WITH_QUANTITY',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  REMOVE_ITEM: 'REMOVE_ITEM'
};

export default CartActionTypes;
