const AdruinoCategoriesActionTypes = {
  FETCH_ARDUINO_CATEGORIES_START: 'FETCH_ARDUINO_CATEGORIES_START',
  FETCH_ARDUINO_CATEGORIES_SUCCESS: 'FETCH_ARDUINO_CATEGORIES_SUCCESS',
  FETCH_ARDUINO_CATEGORIES_FAILURE: 'FETCH_ARDUINO_CATEGORIES_FAILURE'
};

export default AdruinoCategoriesActionTypes;
