const FeaturedCategoriesActionTypes = {
  FETCH_FEATURED_CATEGORIES_START: 'FETCH_FEATURED_CATEGORIES_START',
  FETCH_FEATURED_CATEGORIES_SUCCESS: 'FETCH_FEATURED_CATEGORIES_SUCCESS',
  FETCH_FEATURED_CATEGORIES_FAILURE: 'FETCH_FEATURED_CATEGORIES_FAILURE'
};

export default FeaturedCategoriesActionTypes;
