const PiCategoriesActionTypes = {
  FETCH_PI_CATEGORIES_START: 'FETCH_PI_CATEGORIES_START',
  FETCH_PI_CATEGORIES_SUCCESS: 'FETCH_PI_CATEGORIES_SUCCESS',
  FETCH_PI_CATEGORIES_FAILURE: 'FETCH_PI_CATEGORIES_FAILURE'
};

export default PiCategoriesActionTypes;
